bis-med-it/pysdmx

poetry.lock, pyproject.toml, src/pysdmx/__init__.py
The purpose of this PR is to make the definition of the dependencies a bit more open, so that the library is easier to use in downstream projects.
=> Make library dependencies more generic

SECURITY.md
Updates the contact email address in the security policy to contact.sdmx.io@bis.org as discussed via email.
=> Updates contact email in SECURITY.md

src/pysdmx/model/message.py, tests/model/test_message.py
This PR adds the Message class to the library, which allows the management of different SDMX objects at once, to enable the writing of complex SDMX messages.
Summary:
- Added the Message class and related tests
Closes #42
=> Added message class with the actual content implemented (ItemScheme related)

src/pysdmx/model/map.py, src/pysdmx/util/__init__.py, src/pysdmx/util/_date_pattern_map.py, tests/api/qb/util/test_check_multiple_items.py, tests/model/test_map_date_pattern.py, tests/util/test_date_pattern_map.py
=> Map SDMX date patterns to Python format codes

src/pysdmx/model/category.py, src/pysdmx/model/code.py, src/pysdmx/model/concept.py, tests/model/test_category_scheme.py, tests/model/test_codelist.py, tests/model/test_concept_scheme.py, tests/model/test_hierarchy.py
=> Add __contains__ function to item schemes

src/pysdmx/io/json/sdmxjson2/messages/concept.py, src/pysdmx/model/dataflow.py, src/pysdmx/util/_date_pattern_map.py, tests/api/fmr/samples/pra/schema.fusion.json, tests/api/fmr/schema_checks.py, tests/io/json/sdmxjson2/test_default_data_type.py, tests/model/test_component.py, tests/util/test_date_pattern_map.py
This PR:
- Adds additional checks for pattern mapping;
- Rename component codes to enumeration to avoid confusing case such as comp.codes.codes
Fix #78
=> Minor changes

.github/workflows/ci.yml, src/pysdmx/io/json/sdmxjson2/messages/concept.py, src/pysdmx/io/json/sdmxjson2/messages/core.py, src/pysdmx/io/json/sdmxjson2/messages/dsd.py, src/pysdmx/io/json/sdmxjson2/messages/org.py, src/pysdmx/io/json/sdmxjson2/messages/pa.py, tests/api/fmr/samples/concept/cs.json, tests/api/fmr/samples/df/details.json, tests/api/fmr/samples/df/hierarchy_schema.json, tests/api/fmr/samples/df/no_attr.schema.json, tests/api/fmr/samples/df/no_const.json, tests/api/fmr/samples/df/no_measure.schema.json, tests/api/fmr/samples/df/no_td.json, tests/api/fmr/samples/df/schema.json, tests/api/fmr/samples/orgs/providersflows.json, tests/api/fmr/schema_checks.py, tests/api/fmr/sdmx/test_schemas.py, tests/io/json/sdmxjson2/test_default_data_type.py
=> Fix issues with deserialization of SDMX-JSON output

src/pysdmx/api/fmr/__init__.py, tests/api/fmr/fusion/test_categories.py, tests/api/fmr/sdmx/test_categories.py
=> Add reference and detail params to category scheme queries

src/pysdmx/io/json/fusion/messages/core.py, src/pysdmx/io/json/sdmxjson2/messages/core.py
=> Component is an array only if maxOccurs > 1

src/pysdmx/io/json/sdmxjson2/messages/category.py, src/pysdmx/util/__init__.py, tests/api/fmr/samples/cat/cs.json, tests/util/test_parse_item_urn.py, tests/util/test_parse_urn.py
=> Categorisation target expects a category, and not a structure

src/pysdmx/api/dc/query/__init__.py, src/pysdmx/api/dc/query/util.py, src/pysdmx/io/csv/sdmx10/reader/__init__.py, src/pysdmx/io/csv/sdmx10/writer/__init__.py, src/pysdmx/io/csv/sdmx20/reader/__init__.py, src/pysdmx/io/csv/sdmx20/writer/__init__.py, src/pysdmx/io/pd.py, src/pysdmx/io/xml/sdmx21/reader/data_read.py, src/pysdmx/model/dataset.py, tests/api/dc/test_parser.py, tests/io/csv/sdmx10/writer/test_writer_v1.py, tests/io/csv/sdmx20/writer/test_writer_v2.py, tests/io/test_pandas_dataset.py
=> Fix dependency issues (parsy and pandas)

src/pysdmx/io/json/fusion/messages/code.py, src/pysdmx/io/json/fusion/messages/map.py, src/pysdmx/io/json/fusion/messages/schema.py, src/pysdmx/io/json/sdmxjson2/messages/code.py, src/pysdmx/io/json/sdmxjson2/messages/map.py, src/pysdmx/io/json/sdmxjson2/messages/schema.py, src/pysdmx/model/code.py, src/pysdmx/model/map.py, tests/model/test_hierarchy.py, tests/model/test_map_multi_component_mapper.py, tests/model/test_map_multi_representation_map.py, tests/model/test_map_representation_map.py, tests/model/test_map_single_component_mapper.py, tests/model/test_map_structure_map.py
=> Improve inheritance of model classes that are maintainable artefacts

src/pysdmx/model/dataflow.py, tests/model/test_dataflow_info.py, tests/model/test_map_multi_value_map.py, tests/model/test_map_single_value_map.py, tests/model/test_series_info.py
=> Replace deprecated utcnow()

src/pysdmx/errors.py, tests/model/test_components.py
=> Pass both title and description (if available) to Python error class

src/pysdmx/io/json/fusion/messages/core.py, src/pysdmx/io/json/sdmxjson2/messages/core.py, tests/api/fmr/samples/df/no_const.fusion.json, tests/api/fmr/samples/df/no_const.json
=> Handle case where a component has both a local and a core enumerated representation

src/pysdmx/util/_date_pattern_map.py, tests/model/test_map_date_pattern.py, tests/util/test_date_pattern_map.py
=> yyyy should be mapped to %Y

src/pysdmx/api/fmr/__init__.py, src/pysdmx/io/json/fusion/reader/__init__.py, src/pysdmx/io/json/sdmxjson2/reader/__init__.py, src/pysdmx/io/serde.py
=> Move deserializers below the io package

src/pysdmx/io/json/sdmxjson2/messages/code.py, tests/api/fmr/samples/df/hierarchy_hca.json
=> Fix typo in hierarchy associations in SDMX-JSON

src/pysdmx/model/__base.py, src/pysdmx/model/__init__.py, src/pysdmx/model/organisation.py, tests/model/test_organisation_schemes.py
=> Add missing organisation schemes and organisations

src/pysdmx/io/json/fusion/messages/category.py, src/pysdmx/io/json/fusion/messages/map.py, src/pysdmx/io/json/sdmxjson2/messages/category.py, src/pysdmx/io/json/sdmxjson2/messages/map.py, src/pysdmx/model/__base.py, src/pysdmx/model/__init__.py, src/pysdmx/model/category.py, src/pysdmx/model/code.py, src/pysdmx/model/concept.py, src/pysdmx/model/map.py, tests/api/fmr/code_map_checks.py, tests/api/fmr/mapping_checks.py, tests/model/test_category_scheme.py, tests/model/test_codelist.py, tests/model/test_concept_scheme.py, tests/model/test_dataflow_info.py, tests/model/test_decoders.py, tests/model/test_encoders.py, tests/model/test_hierarchy.py, tests/model/test_map_multi_component_mapper.py, tests/model/test_map_multi_representation_map.py, tests/model/test_map_multi_value_map.py, tests/model/test_map_representation_map.py, tests/model/test_map_single_component_mapper.py, tests/model/test_map_single_value_map.py, tests/model/test_map_structure_map.py, tests/model/test_metadata_report.py, tests/model/test_schema.py
Fix #138 
Fix #139 
Fix #140 
Fix #143
=> Make sure all model classes are serializable and deserializable

src/pysdmx/io/xml/sdmx21/reader/__utils.py, src/pysdmx/io/xml/sdmx21/reader/metadata_read.py, src/pysdmx/model/vtl.py, tests/io/xml/sdmx21/reader/samples/transformation_scheme.xml, tests/io/xml/sdmx21/reader/test_reader.py, tests/model/test_vtl.py
=> 91 implement the vtl artefacts parsers

src/pysdmx/api/fmr/__init__.py, src/pysdmx/io/json/fusion/messages/__init__.py, src/pysdmx/io/json/fusion/messages/category.py, src/pysdmx/io/json/fusion/reader/__init__.py, src/pysdmx/io/json/sdmxjson2/messages/__init__.py, src/pysdmx/io/json/sdmxjson2/messages/category.py, src/pysdmx/io/json/sdmxjson2/reader/__init__.py, src/pysdmx/io/serde.py, src/pysdmx/model/__init__.py, src/pysdmx/model/category.py, tests/api/fmr/categorisation_checks.py, tests/api/fmr/fusion/test_categorisation.py, tests/api/fmr/samples/cat/categorisation.fusion.json, tests/api/fmr/samples/cat/categorisation.json, tests/api/fmr/sdmx/test_categorisation.py
=> Add support for categorisation

README.rst, src/pysdmx/model/__base.py, src/pysdmx/model/category.py, src/pysdmx/model/dataflow.py
Dataflow was allowed in the CategoryScheme but not the Category. This issue has now been addressed.
Also, I have added a badge to awesome official statistical software.
=> Allow both DataflowRef and Dataflow in Category

src/pysdmx/io/json/fusion/messages/code.py, src/pysdmx/io/json/fusion/messages/core.py, src/pysdmx/io/json/sdmxjson2/messages/code.py, tests/api/fmr/samples/code/freq.fusion.json, tests/api/fmr/samples/code/freq.json, tests/api/fmr/samples/pra/hierarchy_hca.fusion.json, tests/api/fmr/samples/pra/no_hca.fusion.json
Fix bug affecting annotations in Fusion-JSON. The Fusion-JSON annotation class expected properties like title to be present but these are optional according to the SDMX information model.
Fix #171
=> Annotations title

.github/workflows/sphinx.yaml
=> Update version of deploy-pages action

src/pysdmx/io/xml/sdmx21/writer/__write_aux.py, src/pysdmx/io/xml/sdmx21/writer/__write_data_aux.py, src/pysdmx/io/xml/sdmx21/writer/error.py, src/pysdmx/io/xml/sdmx21/writer/generic.py, src/pysdmx/io/xml/sdmx21/writer/structure_specific.py, tests/io/xml/sdmx21/writer/test_structures_writing.py, tests/io/xml/sdmx21/writer/test_writing_validation.py
Closes #216
- Fixed placeholder of Error message
- Moved data writers parameters handling to new aux file (__write_data_aux)
- Fixed imports on data writers and tests
=> Refactored SDMX-ML writers to allow writing structures without the data extra

pyproject.toml, src/pysdmx/__init__.py
The purpose of this PR is to set the version to 1.1.1, so that we can release a new version of pysdmx.
=> Bump version to 1.1.1

src/pysdmx/io/xml/sdmx21/__tokens.py, src/pysdmx/io/xml/sdmx21/reader/generic.py, tests/io/xml/sdmx21/reader/test_reader.py
- Changed measure column on SDMX-ML 2.1 Generic reader to OBS_VALUE
- Adapted test to check for this specific column
=> Fixed generic parsing to get OBS_VALUE as column.

src/pysdmx/io/xml/sdmx21/__tokens.py, src/pysdmx/io/xml/sdmx21/reader/__data_aux.py, src/pysdmx/io/xml/sdmx21/reader/generic.py, src/pysdmx/io/xml/sdmx21/reader/structure_specific.py
- Changed tokens names to separate words with _
- Removed non-used tokens and ensure all variables are in capital letters
=> Refactor __tokens to apply naming convention

pyproject.toml, src/pysdmx/__init__.py
The purpose of this PR is to set the version to 1.2.0, ahead of the release later this week.
=> Bump version to 1.2.0

src/pysdmx/api/fmr/__init__.py, tests/api/fmr/agency_checks.py, tests/api/fmr/fusion/test_agencies.py, tests/api/fmr/sdmx/test_agencies.py
The purpose of this PR is to add a timeout to the Registry clients.
=> Add timeout to Registry clients

src/pysdmx/io/xml/sdmx21/reader/header.py, src/pysdmx/io/xml/sdmx21/reader/structure.py, src/pysdmx/io/xml/sdmx21/writer/structure.py, src/pysdmx/model/__base.py, src/pysdmx/model/__init__.py, src/pysdmx/model/dataflow.py, src/pysdmx/model/map.py, src/pysdmx/model/vtl.py, src/pysdmx/toolkit/vtl/_validations.py, src/pysdmx/toolkit/vtl/generate_vtl_script.py, src/pysdmx/util/__init__.py, tests/io/xml/sdmx21/writer/test_structures_writing.py, tests/toolkit/test_generate_vtl_script.py, tests/toolkit/test_validations.py, tests/util/test_parse_item_urn.py, tests/util/test_parse_short_urn.py, tests/util/test_parse_urn.py
Fix #273 
@javihern98, I have moved the references to the __base.py file but happy to discuss if this is not to your liking.
=> Fix circular import error

src/pysdmx/io/xml/sdmx21/reader/header.py, tests/io/xml/sdmx21/reader/samples/header_xmlns.xml, tests/io/xml/sdmx21/reader/test_reader.py
=> Drop warning on xml-related attributes

src/pysdmx/io/xml/__structure_aux_writer.py, tests/io/xml/sdmx21/writer/samples/enum_format.xml, tests/io/xml/sdmx21/writer/test_structures_writing.py
- Changed CoreRepresentation to write EnumerationFormat or TextFormat when needed
=> CoreRepresentation writes TextFormat instead of the expected EnumerationFormat

pyproject.toml, src/pysdmx/__init__.py
Following the successful round of testing, we can now release version 1.4.0
=> Bump version to 1.4.0

src/pysdmx/api/qb/service.py, src/pysdmx/io/input_processor.py, src/pysdmx/io/reader.py, src/pysdmx/util/__init__.py, src/pysdmx/util/_net_utils.py, tests/io/test_general_reader.py
Closes #370 
- Added `pem` argument to read_sdmx
- Ensure we are always using an ssl_context when retrieving from a URL using httpx
- Updated docstrings
=> Added pem file support to read_sdmx and get_datasets.
