pyproject.toml, src/pysdmx/__init__.py, src/pysdmx/model/code.py, tests/model/test_hierarchy.py
Codes within a hierarchy can be retrieved by ID, for example:
```python
code = hierarchy["EU.ES"]
```
However, this requires knowing not only the code ID  (`ES` in the example above), but also the ID of all of its parents (`EU` in the example above).
A method has been added, so as to be able to retrieve codes, when the IDs of the parents are unknown. 
Please not that:
- The method returns a set, to avoid returning the same code more than once, in case it is attached to multiple parents;
- The set may contain more than one code. As a hierarchy can reference codes coming from multiple codelists, we cannot exclude the possibility that codes from different codelists will have the same ID.
=> Find codes by ID

pyproject.toml, src/pysdmx/__init__.py, src/pysdmx/model/code.py, tests/model/test_hierarchy.py
This is a follow-up for PR https://github.com/bis-med-it/pysdmx/pull/14
=> Fix unhashable list

pyproject.toml, src/pysdmx/__init__.py, src/pysdmx/model/code.py, src/pysdmx/util/__init__.py, tests/model/test_hierarchy.py
A utility method has been added, returning all the codes from a hierarchy as a flat list without duplicated entries.
This is useful in case the hierarchy is associated to a component in a dataflow and must be used for validation purposes.
=> Flatten hierarchy

src/pysdmx/model/__base.py, tests/model/test_annotation.py, tests/model/test_maintainable.py
Post init validation checks have been added to:
- Annotations, to make sure at least one property is set
- Maintainable artefacts, to make sure the agency is set
Close #32
Close #34
=> Add post init validation checks

src/pysdmx/fmr/fusion/dsd.py, src/pysdmx/fmr/fusion/schema.py, src/pysdmx/fmr/sdmx/concept.py, src/pysdmx/fmr/sdmx/dsd.py, src/pysdmx/fmr/sdmx/schema.py, src/pysdmx/model/concept.py, src/pysdmx/model/dataflow.py, tests/fmr/samples/df/hierarchy_schema.fusion.json, tests/fmr/samples/df/hierarchy_schema.json, tests/fmr/schema_checks.py, tests/model/test_component.py, tests/model/test_concept.py, tests/model/test_encoders.py
As [discussed](https://github.com/bis-med-it/pysdmx/discussions/31), I have added support for local and core representations. This includes data type, facets and enumeration.
In order to keep the API simple, properties have been added to return the local representation (if set), or the core representation (if set), or the default value in case both are unset. Default value is `None` for facets and enumeration, and `DataType.STRING` for the data type. 
Close #38
=> Add support for core and local representations

src/pysdmx/api/dc/_api.py, src/pysdmx/io/json/fusion/messages/category.py, src/pysdmx/io/json/fusion/messages/dataflow.py, src/pysdmx/io/json/sdmxjson2/messages/category.py, src/pysdmx/io/json/sdmxjson2/messages/dataflow.py, src/pysdmx/model/__base.py, src/pysdmx/model/__init__.py, src/pysdmx/model/category.py, src/pysdmx/model/dataflow.py, tests/model/test_dataflow_ref.py, tests/model/test_organisation.py
The purpose of this PR is to allow distinguishing between:
- A `DataflowRef`, i.e. an SDMX artefact that consists of the information necessary to identify a dataflow (agency, id and version);
- A `Dataflow`, i.e. a maintainable SDMX artefact.
Until now, the 2 were mixed in the code base, which was confusing.
Fix #117
=> Distinguish between Dataflow (Maintainable) and DataflowRef

src/pysdmx/api/qb/__init__.py, src/pysdmx/api/qb/service.py, tests/api/qb/service/test_service_availability.py, tests/api/qb/service/test_service_data.py, tests/api/qb/service/test_service_refmeta.py, tests/api/qb/service/test_service_schema.py, tests/api/qb/service/test_service_structure.py
The purpose of this PR is to complete the work on the SDMX-REST query builders by adding a simple web service class that can be used to execute these queries.
Fix #113
=> Add simple web service client

.github/workflows/ci.yml
Fix 2 issues with CI pipeline:
- A different version of Python was used by pipx than the one specified by the GitHub action;
- MacOS builds were broken (related to the fact that pipx was using Python 3.13 along with poetry);
Unfortunately, this means that the build against 3.13 cannot be enabled yet...
Fix #95
=> Review CI pipeline

.github/workflows/sphinx.yaml
Artifact actions v3 (a dependency of actions/upload-pages-artifact) will be closing down by January 30, 2025. The purpose of this PR is to avoid issues later by switching to the latest version now.
=> Use latest version of action because old one will be removed

src/pysdmx/io/json/fusion/messages/core.py, tests/api/fmr/samples/df/no_const.fusion.json, tests/api/fmr/samples/df/no_const.json, tests/api/fmr/samples/df/schema.fusion.json, tests/api/fmr/samples/df/schema.json, tests/api/fmr/schema_checks.py
The type for minValue, maxValue, startValue and endValue is different between SDMX-JSON and Fusion-JSON (number vs. string). This was causing problems when deserializing objects, when using Fusion-JSON to download the data, as the model class expects an int or a float, but not a string.
=> Deser minval

src/pysdmx/api/qb/service.py
The purpose of this pull request is to add the possibility of setting a timeout when executing a web service query. At the same time, documentation has been improved and a class attribute has been made private.
Closes #193.
=> Add timeout to RestService

src/pysdmx/api/fmr/__init__.py, src/pysdmx/api/qb/__init__.py, src/pysdmx/api/qb/service.py, src/pysdmx/io/format.py, tests/api/qb/refmeta/test_refmeta_format.py, tests/api/qb/schema/test_schema_format.py, tests/api/qb/service/test_service_availability_async.py, tests/api/qb/service/test_service_data_async.py, tests/api/qb/service/test_service_refmeta_async.py, tests/api/qb/service/test_service_schema_async.py, tests/api/qb/service/test_service_structure_async.py
The purpose of this pull request is to:
- Add an aynchronous client for SDMX-REST services
- Replace the httpx code in the `pysdmx.api.fmr` module with the SDMX-REST synchronous and asynchronous clients
Close #194
=> Add asynchronous client for SDMX-REST services

src/pysdmx/io/json/fusion/messages/category.py, src/pysdmx/io/json/fusion/messages/concept.py, src/pysdmx/io/json/fusion/messages/org.py, src/pysdmx/io/json/sdmxjson2/messages/category.py, src/pysdmx/io/json/sdmxjson2/messages/concept.py, src/pysdmx/io/json/sdmxjson2/messages/org.py, tests/api/fmr/agency_checks.py, tests/api/fmr/category_checks.py, tests/api/fmr/concept_checks.py, tests/api/fmr/fusion/test_agencies.py, tests/api/fmr/fusion/test_categories.py, tests/api/fmr/fusion/test_concepts.py, tests/api/fmr/fusion/test_providers.py, tests/api/fmr/provider_checks.py, tests/api/fmr/samples/cat/empty_cs.fusion.json, tests/api/fmr/samples/cat/empty_cs.json, tests/api/fmr/samples/concept/empty_cs.fusion.json, tests/api/fmr/samples/concept/empty_cs.json, tests/api/fmr/samples/orgs/empty_agencies.fusion.json, tests/api/fmr/samples/orgs/empty_agencies.json, tests/api/fmr/samples/orgs/empty_providers.fusion.json, tests/api/fmr/samples/orgs/empty_providers.json, tests/api/fmr/sdmx/test_agencies.py, tests/api/fmr/sdmx/test_categories.py, tests/api/fmr/sdmx/test_concepts.py, tests/api/fmr/sdmx/test_providers.py
The SDMX-JSON and Fusion-JSON deserializers could not handle empty item schemes for certain types of item schemes. The affected types were: category schemes, concept schemes, agency schemes and data provider schemes. Codelists, value lists and hierarchies were not affected.
Close #191
=> Handle empty item schemes in SDMX-JSON and Fusion-JSON

CHANGELOG.rst, docs/release.rst, pyproject.toml, src/pysdmx/__init__.py
This PR:
- Bumps the version number
- Adds a release note for 1.1.0
- Sets the development status to Production/Stable
=> Prepare release of v1.1.0

src/pysdmx/io/xml/sdmx21/writer/__write_aux.py, src/pysdmx/io/xml/sdmx21/writer/generic.py, src/pysdmx/io/xml/sdmx21/writer/structure.py, src/pysdmx/io/xml/sdmx21/writer/structure_specific.py, tests/io/xml/sdmx21/writer/samples/bis_der.xml, tests/io/xml/sdmx21/writer/samples/estat_sample.xml, tests/io/xml/sdmx21/writer/test_data_writing.py, tests/io/xml/sdmx21/writer/test_structures_writing.py
Closes #215 
Added a escape function on data writing and structures writing to ensure text is escaped when necessary (&,  > and < is converted to &amp; &gt; &lt;)
Added a sample file from ESTAT as this agency normally has these kind of characters in annotations, edited to include them in Names and Descriptions.
=> Add escape function to SDMX-ML writers

src/pysdmx/io/xml/sdmx21/reader/generic.py, src/pysdmx/io/xml/sdmx21/reader/structure_specific.py, src/pysdmx/io/xml/sdmx21/writer/__write_aux.py, tests/io/xml/sdmx21/writer/test_data_writing.py
Closes #217 
- Fixed Header order and added test to write and read empty data. 
- Ensure we write a Header with Source and references that is valid against the SDMX-ML 2.1 XSD.
=> Fix Header order on Source and add compatibility for empty data on SDMX-ML Data messages

src/pysdmx/io/xml/sdmx21/writer/__write_aux.py, src/pysdmx/io/xml/sdmx21/writer/generic.py, tests/api/qb/registration/test_regctx_query_updated_before.py, tests/api/qb/registration/test_regprv_query_updated_before.py, tests/io/xml/sdmx21/writer/test_data_writing.py
Closes #209 
Added a check to ensure the optional attributes are present inside the data, if not, the attributes should not be added to series_codes and obs_codes.
The two test files are just format changes (from another branch maybe?)
=> Fixed bug on writing SDMX ML file with optional attributes

src/pysdmx/io/csv/sdmx10/reader/__init__.py, src/pysdmx/io/csv/sdmx20/reader/__init__.py, tests/io/csv/sdmx10/reader/test_reader_v1.py, tests/io/csv/sdmx20/reader/test_reader_v2.py
Close #214
- Removed dataset attribtues parsing on SDMX-CSV readers (version 1.0 and 2.0)
- Changed tests to ensure we do not read any dataset attributes in these formats
=> Removed dataset attributes parsing on SDMX-CSV readers.

src/pysdmx/io/xml/sdmx21/reader/generic.py, src/pysdmx/io/xml/sdmx21/reader/structure_specific.py, src/pysdmx/io/xml/sdmx21/writer/__write_aux.py, src/pysdmx/io/xml/sdmx21/writer/generic.py, src/pysdmx/io/xml/sdmx21/writer/structure.py, src/pysdmx/io/xml/sdmx21/writer/structure_specific.py, src/pysdmx/model/dataset.py, src/pysdmx/model/message.py, tests/io/xml/sdmx21/writer/test_data_writing.py, tests/io/xml/sdmx21/writer/test_structures_writing.py
Close #211 
- Added dataset action and dataset id to SDMX-ML data writers
- Added better handling of dataset qualifiers on SDMX-ML structure specific writer
- Prevent the use of dataset id and dataset action in SDMX-ML Structures writer
=> Implemented dataset action and dataset id on header. Added action attribute to dataset on SDMX-ML data writers

src/pysdmx/api/fmr/__init__.py, src/pysdmx/io/json/fusion/messages/org.py, src/pysdmx/io/json/sdmxjson2/messages/org.py, src/pysdmx/model/organisation.py, tests/api/fmr/provider_checks.py, tests/model/test_organisation_schemes.py
This PR adds support for handling JSON responses with multiple agency or data provider schemes. 
The support has been added in a backward-compatible way, i.e. the `fmr` module is not affected.
In addition, utility methods have been added to the organisation schemes (e.g. `__len__` etc), thereby aligning them with the other item schemes.
Close #224
=> Handle multiple agency and data provider schemes

src/pysdmx/io/xml/sdmx21/reader/generic.py, tests/io/xml/sdmx21/reader/test_reader.py
Closes #225 
Fixed small bug on SDMX-ML 2.1 Generic Series writing and ensure we have the Dimension At Observation at the Dataframe columns.
=> Replaced ObsDimension with the Dimension At Observation on the SDMX-ML Generic Series reader

poetry.lock, pyproject.toml
This PR:
- Upgrades `httpx` (and related test dependencies, i.e. `respx`)
- Like for `msgspec`, we now accept any version matching 0.*
=> Upgrade httpx

poetry.lock
The purpose of this PR is to patch a vulnerability in h11.
There was a PR from Dependabot but, somehow, it had more changes than expected and so I redid the patch myself.
=> Upgrade h11 to 0.16.0

src/pysdmx/io/json/fusion/messages/report.py, src/pysdmx/io/json/sdmxjson2/messages/report.py, src/pysdmx/model/metadata.py, tests/api/fmr/report_checks.py, tests/api/fmr/samples/refmeta/report.fusion.json, tests/api/fmr/samples/refmeta/report.json, tests/model/test_metadata_report.py
The purpose of this PR is to add the version attribute to metadata reports. Both the model class and the FMR json deserializers have been updated.
Close #279
=> Add version to metadata reports

docs/api/query/registration.rst, docs/api/rest.rst, src/pysdmx/api/qb/refmeta.py, src/pysdmx/api/qb/structure.py, tests/api/qb/refmeta/test_refmeta_mds_query_factory.py, tests/api/qb/structure/test_structure_query_factory.py
This PR adds a factory method to `StructureQuery` and `RefMetaByMetadatasetQuery`. The factory methods allow creating an instance of these queries out of a reference object or an SDMX URN.
Close #289
=> Build a Query object out of an SDMX Reference or a URN

src/pysdmx/io/xml/sdmx21/reader/generic.py, tests/io/xml/sdmx21/reader/samples/gen_all.xml, tests/io/xml/sdmx21/reader/samples/gen_ser.xml
- Added inline if to ensure we read an empty value when the ObsValue tag is missing
- Modified SDMX-ML 2.1 Generic test files to cover this case
=> Failure to read SDMX-ML 2.1 Generic message when Obs has no ObsValue

src/pysdmx/io/xml/__structure_aux_writer.py, tests/io/xml/sdmx21/writer/test_structures_writing.py
- Added an error message to prevent writing SDMX-ML 2.1 when a DataStructureDefinition has multiple measures
- Refactored name of variable in write_components
=> Raise an error when trying to write a DataStructureDefinition with more than one measure in SDMX-ML 2.1

src/pysdmx/io/input_processor.py
This affects version `1.5.0`
- Removed the xml import from input_processor
=> pysdmx should not require xml extras
